plugins {
    id 'java'
}

def versionPropsFile = file('version.properties')
def buildNumber = 1

if (versionPropsFile.exists()) {
    def versionProps = new Properties()
    versionPropsFile.withInputStream { versionProps.load(it) }
    buildNumber = (versionProps.getProperty('buildNumber') ?: '0').toInteger()
}

// Increment version number on jar/build execution
gradle.taskGraph.whenReady { taskGraph ->
    if (taskGraph.hasTask(":BuildCam-FPV:jar") || taskGraph.hasTask(":BuildCam-FPV:build")) {
        buildNumber++
        def versionProps = new Properties()
        versionProps.setProperty('buildNumber', buildNumber.toString())
        versionPropsFile.withOutputStream { versionProps.store(it, null) }
    }
}

group = 'com.technical.buildcamfpv'
version = "1.0.${buildNumber}"

repositories {
    mavenCentral()
    maven {
        name = 'papermc'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    implementation 'io.papermc.paper:paper-api:1.20.4-R0.1-SNAPSHOT'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.2'
}

def targetJavaVersion = 17
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

test {
    useJUnitPlatform()
}
